theme: jekyll-theme-minimal
logo: matt-cropped.jpg
title: Matt J. Davidson
custom_title: Matt J. Davidson
description: <a href="http://mypronouns.org/he">(he/him/his pronouns)</a> <br><a href="matt davidson cv 5-1-21.pdf">cv</a> | <a href="mailto:mattjd@uw.edu">email </a> | <a href="https://www.linkedin.com/in/matt-davidson-he-him-92379916/">linkedin</a> | <a href="https://www.twitter.com/dontmattme/">twitter</a></br>
